import type { BalancerCustomStatus } from "@/types/balancer-admin.types";
import type { StatusMeta, StatusScope } from "@/types/registration.types";

const BUILTIN_STATUS_META: Record<StatusScope, StatusMeta[]> = {
  registration: [
    {
      value: "pending",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "Clock",
      icon_color: "#f59e0b",
      name: "Pending",
      description: "Waiting for moderator review.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "approved",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "CheckCircle2",
      icon_color: "#10b981",
      name: "Approved",
      description: "Registration approved.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "rejected",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "XCircle",
      icon_color: "#ef4444",
      name: "Rejected",
      description: "Registration rejected.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "withdrawn",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "Undo2",
      icon_color: "#94a3b8",
      name: "Withdrawn",
      description: "Registration withdrawn.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "banned",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "ShieldBan",
      icon_color: "#ef4444",
      name: "Banned",
      description: "Registration blocked.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "insufficient_data",
      scope: "registration",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "AlertTriangle",
      icon_color: "#f97316",
      name: "Incomplete",
      description: "Registration data is incomplete.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
  ],
  balancer: [
    {
      value: "not_in_balancer",
      scope: "balancer",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "MinusCircle",
      icon_color: "#94a3b8",
      name: "Not Added",
      description: "Registration has not been added to the balancer pool yet.",
      excludes_from_balancer: true,
      excludes_from_ready: false,
    },
    {
      value: "excluded",
      scope: "balancer",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "ShieldOff",
      icon_color: "#ef4444",
      name: "Excluded",
      description: "Manually removed from the balancer pool after being added.",
      excludes_from_balancer: true,
      excludes_from_ready: false,
    },
    {
      value: "incomplete",
      scope: "balancer",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "AlertTriangle",
      icon_color: "#f97316",
      name: "Incomplete",
      description: "Registration needs rank or role fixes.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
    {
      value: "ready",
      scope: "balancer",
      is_builtin: true,
      kind: "builtin",
      is_override: false,
      can_edit: true,
      can_delete: false,
      can_reset: false,
      icon_slug: "CheckCircle2",
      icon_color: "#10b981",
      name: "Ready",
      description: "Registration is ready for balancer.",
      excludes_from_balancer: false,
      excludes_from_ready: false,
    },
  ],
};

export function mergeStatusOptions(
  scope: StatusScope,
  customStatuses: BalancerCustomStatus[] | undefined,
): { system: StatusMeta[]; custom: StatusMeta[] } {
  const scopedStatuses = (customStatuses ?? []).filter((status) => status.scope === scope);
  const systemOverrides = scopedStatuses
    .filter((status) => status.kind === "builtin")
    .map((status) => ({
      value: status.slug,
      scope: status.scope,
      is_builtin: true,
      kind: "builtin" as const,
      is_override: status.is_override,
      can_edit: true,
      can_delete: false,
      can_reset: status.can_reset,
      icon_slug: status.icon_slug,
      icon_color: status.icon_color,
      name: status.name,
      description: status.description,
      // Builtin overrides never carry their own exclusion semantics -- both
      // are fixed by BUILTIN_STATUS_META, not admin-editable. Fall back to
      // false only if the builtin slug is somehow unknown (defensive).
      excludes_from_balancer:
        BUILTIN_STATUS_META[scope].find((builtin) => builtin.value === status.slug)?.excludes_from_balancer ?? false,
      excludes_from_ready:
        BUILTIN_STATUS_META[scope].find((builtin) => builtin.value === status.slug)?.excludes_from_ready ?? false,
    }));
  const mergedSystem = BUILTIN_STATUS_META[scope].map((builtin) => {
    const override = systemOverrides.find((status) => status.value === builtin.value);
    return override ?? builtin;
  });

  return {
    system: mergedSystem,
    custom: scopedStatuses
      .filter((status) => status.kind === "custom")
      .map((status) => ({
        value: status.slug,
        scope: status.scope,
        is_builtin: false,
        kind: "custom" as const,
        is_override: false,
        can_edit: true,
        can_delete: true,
        can_reset: false,
        icon_slug: status.icon_slug,
        icon_color: status.icon_color,
        name: status.name,
        description: status.description,
        excludes_from_balancer: status.excludes_from_balancer,
        excludes_from_ready: status.excludes_from_ready,
      })),
  };
}
