from __future__ import annotations

# Auto-generated from legacy achievement consts during engine migration.
# Source removed from runtime; seeder consumes this catalog as canonical metadata.

CANONICAL_ACHIEVEMENT_CATALOG: tuple[dict[str, str], ...] = (
    {'category': 'hero',
 'slug': 'dva',
 'name': 'Nerf this!',
 'description_ru': 'Иметь лучшее K/D на Диве за турнир',
 'description_en': 'Have the best K/D as D.Va during the tournament'},
    {'category': 'hero',
 'slug': 'doomfist',
 'name': 'ANDTHEYSAY',
 'description_ru': 'Иметь лучшее K/D на Думфисте за турнир',
 'description_en': 'Have the best K/D as Doomfist during the tournament'},
    {'category': 'hero',
 'slug': 'lucio',
 'name': 'A C C E L E R A N D O',
 'description_ru': 'Иметь лучшее K/D на Люсио за турнир',
 'description_en': 'Have the best K/D as Lúcio during the tournament'},
    {'category': 'hero',
 'slug': 'tracer',
 'name': 'Déjà vu',
 'description_ru': 'Иметь лучшее K/D на Трейсер за турнир',
 'description_en': 'Have the best K/D as Tracer during the tournament'},
    {'category': 'hero',
 'slug': 'soldier-76',
 'name': 'That’s "SIR" to you',
 'description_ru': 'Иметь лучшее K/D на Солдате за турнир',
 'description_en': 'Have the best K/D as Soldier: 76 during the tournament'},
    {'category': 'hero',
 'slug': 'genji',
 'name': 'Mada Mada',
 'description_ru': 'Иметь лучшее K/D на Генжи за турнир',
 'description_en': 'Have the best K/D as Genji during the tournament'},
    {'category': 'hero',
 'slug': 'winston',
 'name': 'W I N T O N',
 'description_ru': 'Иметь лучшее K/D на Винтоне за турнир',
 'description_en': 'Have the best K/D as Winston during the tournament'},
    {'category': 'hero',
 'slug': 'hanzo',
 'name': 'Simple geometry',
 'description_ru': 'Иметь лучшее K/D на Ханзо за турнир',
 'description_en': 'Have the best K/D as Hanzo during the tournament'},
    {'category': 'hero',
 'slug': 'mercy',
 'name': 'Heroes never die',
 'description_ru': 'Иметь лучшее K/D на Мерси за турнир',
 'description_en': 'Have the best K/D as Mercy during the tournament'},
    {'category': 'hero',
 'slug': 'ana',
 'name': 'Everyone dies',
 'description_ru': 'Иметь лучшее K/D на Ане за турнир',
 'description_en': 'Have the best K/D as Ana during the tournament'},
    {'category': 'hero',
 'slug': 'sojourn',
 'name': 'THIS ENDS NOW',
 'description_ru': 'Иметь лучшее K/D на Соджорн за турнир',
 'description_en': 'Have the best K/D as Sojourn during the tournament'},
    {'category': 'hero',
 'slug': 'kiriko',
 'name': 'Кокоё',
 'description_ru': 'Иметь лучшее K/D на Кирико за турнир',
 'description_en': 'Have the best K/D as Kiriko during the tournament'},
    {'category': 'hero',
 'slug': 'reaper',
 'name': 'DIE DIE DIE',
 'description_ru': 'Иметь лучшее K/D на Рипере за турнир',
 'description_en': 'Have the best K/D as Reaper during the tournament'},
    {'category': 'hero',
 'slug': 'orisa',
 'name': 'Боевой конь',
 'description_ru': 'Иметь лучшее K/D на Орисе за турнир',
 'description_en': 'Have the best K/D as Orisa during the tournament'},
    {'category': 'hero',
 'slug': 'zarya',
 'name': 'Огонь по готовности!',
 'description_ru': 'Иметь лучшее K/D на Заре за турнир',
 'description_en': 'Have the best K/D as Zarya during the tournament'},
    {'category': 'hero',
 'slug': 'pharah',
 'name': 'Курарефан1',
 'description_ru': 'Иметь лучшее K/D на Фарре за турнир',
 'description_en': 'Have the best K/D as Pharah during the tournament'},
    {'category': 'hero',
 'slug': 'bastion',
 'name': 'За победу мать продам',
 'description_ru': 'Иметь лучшее K/D на Бастионе за турнир',
 'description_en': 'Have the best K/D as Bastion during the tournament'},
    {'category': 'hero',
 'slug': 'junkrat',
 'name': 'Специалист по взрывам',
 'description_ru': 'Иметь лучшее K/D на Джанкрете за турнир',
 'description_en': 'Have the best K/D as Junkrat during the tournament'},
    {'category': 'hero',
 'slug': 'widowmaker',
 'name': 'Hey bro, nice ass',
 'description_ru': 'Иметь лучшее K/D на Видоу за турнир',
 'description_en': 'Have the best K/D as Widowmaker during the tournament'},
    {'category': 'hero',
 'slug': 'baptiste',
 'name': 'Maximum efficiency',
 'description_ru': 'Иметь лучшее K/D на Баптисте за турнир',
 'description_en': 'Have the best K/D as Baptiste during the tournament'},
    {'category': 'hero',
 'slug': 'ashe',
 'name': 'BOOOOOOB!!!',
 'description_ru': 'Иметь лучшее K/D на Аше за турнир',
 'description_en': 'Have the best K/D as Ashe during the tournament'},
    {'category': 'hero',
 'slug': 'cassidy',
 'name': 'Собака сутулая',
 'description_ru': 'Иметь лучшее K/D на МакКри за турнир',
 'description_en': 'Have the best K/D as Cassidy during the tournament'},
    {'category': 'hero',
 'slug': 'ramattra',
 'name': 'SUFFER AS I HAD!',
 'description_ru': 'Иметь лучшее K/D на Рамматре за турнир',
 'description_en': 'Have the best K/D as Ramattra during the tournament'},
    {'category': 'hero',
 'slug': 'lifeweaver',
 'name': 'цветочек))',
 'description_ru': 'Иметь лучшее K/D на ЛайфВивере за турнир',
 'description_en': 'Have the best K/D as Lifeweaver during the tournament'},
    {'category': 'hero',
 'slug': 'illari',
 'name': 'Солнце взошло',
 'description_ru': 'Иметь лучшее K/D на Иллари за турнир',
 'description_en': 'Have the best K/D as Illari during the tournament'},
    {'category': 'hero',
 'slug': 'sigma',
 'name': 'Get rocked',
 'description_ru': 'Иметь лучшее K/D на Сигме за турнир',
 'description_en': 'Have the best K/D as Sigma during the tournament'},
    {'category': 'hero',
 'slug': 'wrecking-ball',
 'name': 'Шароеб',
 'description_ru': 'Иметь лучшее K/D на Хомяке за турнир',
 'description_en': 'Have the best K/D as Wrecking Ball during the tournament'},
    {'category': 'hero',
 'slug': 'mei',
 'name': 'A-MEI-ZING',
 'description_ru': 'Иметь лучшее K/D на Мей за турнир',
 'description_en': 'Have the best K/D as Mei during the tournament'},
    {'category': 'hero',
 'slug': 'symmetra',
 'name': 'Назад в будущее',
 'description_ru': 'Иметь лучшее K/D на Симметре за турнир',
 'description_en': 'Have the best K/D as Symmetra during the tournament'},
    {'category': 'hero',
 'slug': 'zenyatta',
 'name': 'Experience my ass',
 'description_ru': 'Иметь лучшее K/D на Дзене за турнир',
 'description_en': 'Have the best K/D as Zenyatta during the tournament'},
    {'category': 'hero',
 'slug': 'torbjorn',
 'name': 'Cummaster',
 'description_ru': 'Иметь лучшее K/D на Торбе за турнир',
 'description_en': 'Have the best K/D as Torbjörn during the tournament'},
    {'category': 'hero',
 'slug': 'junker-queen',
 'name': 'Женщина мечты',
 'description_ru': 'Иметь лучшее K/D на Квине за турнир',
 'description_en': 'Have the best K/D as Junker Queen during the tournament'},
    {'category': 'hero',
 'slug': 'echo',
 'name': 'Лучшая муха помойки',
 'description_ru': 'Иметь лучшее K/D на Эхо за турнир',
 'description_en': 'Have the best K/D as Echo during the tournament'},
    {'category': 'hero',
 'slug': 'reinhardt',
 'name': 'ПИВО!',
 'description_ru': 'Иметь лучшее K/D на Рейне за турнир',
 'description_en': 'Have the best K/D as Reinhardt during the tournament'},
    {'category': 'hero',
 'slug': 'moira',
 'name': 'Пыль в дымоход',
 'description_ru': 'Иметь лучшее K/D на Мойре за турнир',
 'description_en': 'Have the best K/D as Moira during the tournament'},
    {'category': 'hero',
 'slug': 'sombra',
 'name': 'Кошкодевочка',
 'description_ru': 'Иметь лучшее K/D на Сомбре за турнир',
 'description_en': 'Have the best K/D as Sombra during the tournament'},
    {'category': 'hero',
 'slug': 'roadhog',
 'name': '👍 👍 👍',
 'description_ru': 'Иметь лучшее K/D на Хоге за турнир',
 'description_en': 'Have the best K/D as Roadhog during the tournament'},
    {'category': 'hero',
 'slug': 'brigitte',
 'name': 'АЛЛАХ ТИЛЬМЕ',
 'description_ru': 'Иметь лучшее K/D на Бриге за турнир',
 'description_en': 'Have the best K/D as Brigitte during the tournament'},
    {'category': 'hero',
 'slug': 'mauga',
 'name': 'СЕ СЕ КИ КИ',
 'description_ru': 'Иметь лучшее K/D на Мауге за турнир',
 'description_en': 'Have the best K/D as Mauga during the tournament'},
    {'category': 'hero',
 'slug': 'venture',
 'name': 'Профессиональный крот',
 'description_ru': 'Иметь лучшее K/D на Вентуре за турнир',
 'description_en': 'Have the best K/D as Venture during the tournament'},
    {'category': 'hero',
 'slug': 'juno',
 'name': 'Я могу и так',
 'description_ru': 'Иметь лучшее K/D на Юне за турнир',
 'description_en': 'Have the best K/D as Juno during the tournament'},
    {'category': 'hero',
 'slug': 'hazard',
 'name': 'Я и есть опасность',
 'description_ru': 'Иметь лучшее K/D на Азарте за турнир',
 'description_en': 'Have the best K/D as Hazard during the tournament'},
    {'category': 'hero',
 'slug': 'freak',
 'name': 'Фрик',
 'description_ru': 'Сыграть на персонаже с пикрейтом менее 0.1% в течение турнира.',
 'description_en': 'Play a character with a pickrate of less than 0.1% during the tournament.'},
    {'category': 'hero',
 'slug': 'mystery-heroes',
 'name': 'Мистери хироус',
 'description_ru': 'Отыграть турнир минимум 7 героями.',
 'description_en': 'Play the tournament with at least 7 heroes.'},
    {'category': 'hero',
 'slug': 'swiss-knife',
 'name': 'Человек Швейцарский нож',
 'description_ru': 'За всю историю логов сыграть минимум на 20 разных героях.',
 'description_en': 'Play at least 20 different heroes in the history of logs.'},
    {'category': 'hero',
 'slug': 'freja',
 'name': 'Bounty Hunter',
 'description_ru': 'Иметь лучшее K/D на Фрейе за турнир',
 'description_en': 'Have the best K/D as Freja during the tournament'},
    {'category': 'hero',
 'slug': 'wuyang',
 'name': 'Водник',
 'description_ru': 'Иметь лучшее K/D на У Ян за турнир',
 'description_en': 'Have the best K/D as Wuyang during the tournament'},
    {'category': 'hero',
 'slug': 'vendetta',
 'name': 'Инкредибили',
 'description_ru': 'Иметь лучшее K/D на Вендетте за турнир',
 'description_en': 'Have the best K/D as Vendetta during the tournament'},
    {'category': 'hero',
 'slug': 'emre',
 'name': 'Найду и выебу',
 'description_ru': 'Иметь лучшее K/D на Эмре за турнир',
 'description_en': 'Have the best K/D as Emre during the tournament'},
    {'category': 'hero',
 'slug': 'mizuki',
 'name': 'Ну это шляпа',
 'description_ru': 'Иметь лучшее K/D на Мидзуки за турнир',
 'description_en': 'Have the best K/D as Mizuki during the tournament'},
    {'category': 'hero',
 'slug': 'anran',
 'name': 'С дымком',
 'description_ru': 'Иметь лучшее K/D на Анране за турнир',
 'description_en': 'Have the best K/D as Anran during the tournament'},
    {'category': 'hero',
 'slug': 'domina',
 'name': 'Hot Mommy',
 'description_ru': 'Иметь лучшее K/D на Домине за турнир',
 'description_en': 'Have the best K/D as Domina during the tournament'},
    {'category': 'hero',
 'slug': 'jetpack-cat',
 'name': 'Пушистый Гандон',
 'description_ru': 'Иметь лучшее K/D на Реактивной Кисе за турнир',
 'description_en': 'Have the best K/D as Jetpack Cat during the tournament'},
    {'category': 'overall',
 'slug': 'welcome',
 'name': 'Добро пожаловать в клуб',
 'description_ru': 'Принять участие в турнире любым способом.',
 'description_en': 'Take part in the tournament in any way.'},
    {'category': 'overall',
 'slug': 'honor-and-glory',
 'name': 'ЗА ЧЕСТЬ И СЛАВУ',
 'description_ru': 'Выиграть турнир.',
 'description_en': 'Win the tournament.'},
    {'category': 'overall',
 'slug': 'versatile-player',
 'name': 'Универсальный игрок',
 'description_ru': 'Отыграть 3 турнира на трёх разных ролях.',
 'description_en': 'Play 3 tournaments in three different roles.'},
    {'category': 'overall',
 'slug': 'two-wins-players',
 'name': 'Это не удача, это скилл!',
 'description_ru': 'Выиграть турнир 2 раза.',
 'description_en': 'Win the tournament 2 times.'},
    {'category': 'overall',
 'slug': 'three-wins-players',
 'name': 'ТАГАНРООООООГ',
 'description_ru': 'Выиграть турнир 3 раза.',
 'description_en': 'Win the tournament 3 times.'},
    {'category': 'overall',
 'slug': 'sisyphus-and-stone',
 'name': 'Сизиф и камень',
 'description_ru': 'Занять второе место более двух раз.',
 'description_en': 'Take second place more than two times.'},
    {'category': 'overall',
 'slug': 'old',
 'name': 'Олд',
 'description_ru': 'Сыграть турнир в OW1.',
 'description_en': 'Play a tournament in OW1.'},
    {'category': 'overall',
 'slug': 'young-blood',
 'name': 'Молодая кровь',
 'description_ru': 'Сыграть турнир в OW2.',
 'description_en': 'Play a tournament in OW2.'},
    {'category': 'overall',
 'slug': 'dahao',
 'name': 'ЛУПИ ИХ ДАХАО💪🏻😈🤙🏻 МЕСИ ИХ ДАХАО💪🏻😈🤙🏻',
 'description_ru': 'Выиграть турнир на двух разных ролях.',
 'description_en': 'Win a tournament in two different roles.'},
    {'category': 'overall',
 'slug': 'pathological-sucker',
 'name': 'Патологический лох',
 'description_ru': 'Занять второе место на всех ролях.',
 'description_en': 'Take second place in all roles.'},
    {'category': 'overall',
 'slug': 'lord-of-all-the-elements',
 'name': 'Властелин всех стихий',
 'description_ru': 'Выиграть турнир на трех разных ролях.',
 'description_en': 'Win a tournament in three different roles.'},
    {'category': 'overall',
 'slug': 'backyard-cyber-athlete',
 'name': 'Дворовой киберспортсмен',
 'description_ru': 'Играл OWAL.',
 'description_en': 'Played OWAL.'},
    {'category': 'overall',
 'slug': 'well-deserved-anomaly',
 'name': 'Заслужанная аномалия',
 'description_ru': 'Победитель OWAL.',
 'description_en': 'Winner of OWAL.'},
    {'category': 'overall',
 'slug': 'its-genetics',
 'name': 'Это генетика',
 'description_ru': 'Отыграть все турниры 1 героем',
 'description_en': 'Play all tournaments with 1 hero'},
    {'category': 'overall',
 'slug': 'captain-jack-sparrow',
 'name': 'Капитан Джек Воробей',
 'description_ru': 'Стать капитаном в своей команде.',
 'description_en': 'Become a captain in your team.'},
    {'category': 'overall',
 'slug': 'worst-player-winrate',
 'name': 'Джентльмен неудачи',
 'description_ru': 'Войти в топ20 игроков по винрейту (снизу).',
 'description_en': 'Enter the top 20 players by winrate (from the bottom).'},
    {'category': 'overall',
 'slug': 'best-player-winrate',
 'name': 'Все просто, я лучший!',
 'description_ru': 'Войти в топ20 игроков по винрейту.',
 'description_en': 'Enter the top 20 players by winrate.'},
    {'category': 'overall',
 'slug': 'consistent-winner',
 'name': 'Стабильный победитель',
 'description_ru': 'Занять место в топ20 по выигранным картам.',
 'description_en': 'Take a place in the top 20 by won maps.'},
    {'category': 'overall',
 'slug': 'just-shooting',
 'name': 'Мы просто стреляли пули',
 'description_ru': 'Выиграть турнир с винрейтом 90%+.',
 'description_en': 'Win a tournament with a winrate of 90%+.'},
    {'category': 'overall',
 'slug': 'ill-definitely-survive',
 'name': 'Я обязательно выживу',
 'description_ru': 'Занять топ 1 по минимальному кол-ву смертей в логах турика.',
 'description_en': 'Take top 1 by the minimum number of deaths in the logs of the tournament.'},
    {'category': 'overall',
 'slug': 'killer-machine',
 'name': 'Машина убийца',
 'description_ru': 'Занять топ 1 по максимальному кол-ву убийств в логах турика.',
 'description_en': 'Take top 1 by the maximum number of kills in the logs of the tournament.'},
    {'category': 'overall',
 'slug': 'just-shoot-in-the-head',
 'name': 'Просто стреляй в голову',
 'description_ru': 'Занять топ 1 по кол-ву хедшотов в логах турика.',
 'description_en': 'Take top 1 by the number of headshots in the logs of the tournament.'},
    {'category': 'overall',
 'slug': 'poop_forever',
 'name': 'Срать вечно',
 'description_ru': 'Нанести наибольшее количество урона/мин за турнир',
 'description_en': 'Deal the most damage/min per tournament'},
    {'category': 'overall',
 'slug': 'one-shot-one-kill',
 'name': 'Один выстрел, один труп',
 'description_ru': 'Стать топ 1 по крит. меткости в прицеле на турнире',
 'description_en': 'Become the top 1 by crit accuracy in the sight during the tournament'},
    {'category': 'overall',
 'slug': 'space-created',
 'name': 'Спейс создан',
 'description_ru': 'Умереть 1000+ раз за историю логов',
 'description_en': 'Die 1000+ times in the history of logs'},
    {'category': 'overall',
 'slug': 'fucking-casino-mouth',
 'name': 'ё#%ный рот этого казино',
 'description_ru': 'Сыграть 20 турниров',
 'description_en': 'Play 20 tournaments'},
    {'category': 'overall',
 'slug': 'regular-boar',
 'name': 'Завсегдатай кабанения',
 'description_ru': 'Сыграть 30 турниров',
 'description_en': 'Play 30 tournaments'},
    {'category': 'division',
 'slug': 'my-strength-is-growing',
 'name': 'Моя сила растёт',
 'description_ru': 'Получить плюс див после турнира.',
 'description_en': 'Get a plus div after the tournament.'},
    {'category': 'division',
 'slug': 'not-good-enough',
 'name': 'Недостаточно хорош',
 'description_ru': 'Получить минус див после турнира.',
 'description_en': 'Get a minus div after the tournament.'},
    {'category': 'division',
 'slug': 'i-need-more-power',
 'name': 'Мне нужно больше силы',
 'description_ru': 'Получить 3 див или выше.',
 'description_en': 'Get 3 div or higher.'},
    {'category': 'division',
 'slug': 'my-drill-will-pierce-the-sky',
 'name': 'Мой бур пронзит небеса',
 'description_ru': 'Поднял за время турниров 10+ дивизионов.',
 'description_en': 'Raised 10+ divisions during the tournaments.'},
    {'category': 'division',
 'slug': 'balance-from-anak',
 'name': 'Баланс от Анака',
 'description_ru': 'Получил +4 или больше дивов за турнир.',
 'description_en': 'Got +4 or more divs for the tournament.'},
    {'category': 'division',
 'slug': 'critical-failure',
 'name': 'Критический провал',
 'description_ru': 'Получил -4 или больше дивов за турнир.',
 'description_en': 'Got -4 or more divs for the tournament.'},
    {'category': 'division',
 'slug': 'im-fine-with-that',
 'name': 'Да мне и так нормально...',
 'description_ru': 'Иметь один и тот же дивизион в течении 7+ турниров.',
 'description_en': 'Have the same division for 7+ tournaments.'},
    {'category': 'team',
 'slug': 'accuracy-is-above-all-else',
 'name': 'Точность превыше всего',
 'description_ru': 'Заролиться в команду с двумя хитсканами.',
 'description_en': 'Roll into a team with two hitscans.'},
    {'category': 'team',
 'slug': 'simple-geometry',
 'name': 'Простая геометрия',
 'description_ru': 'Заролиться в команду с двумя проджектайл дд.',
 'description_en': 'Roll into a team with two projectile dps.'},
    {'category': 'team',
 'slug': 'no_mercy',
 'name': 'Мерси не ожидается',
 'description_ru': 'Заролиться в команду с двумя мейн саппортами.',
 'description_en': 'Roll into a team with two main supports.'},
    {'category': 'team',
 'slug': 'heal_for_a_fee',
 'name': 'Хил платно',
 'description_ru': 'Заролиться в команду с двумя лайт хилами.',
 'description_en': 'Roll into a team with two light healers.'},
    {'category': 'team',
 'slug': 'damage-above-5-division',
 'name': 'Киберкотлета с пюрешкой',
 'description_ru': 'Попасть в команду к капитану дд 5 дива и выше.',
 'description_en': 'Get into a team with a captain dps 5 div and above.'},
    {'category': 'team',
 'slug': 'tank-above-5-division',
 'name': 'Беру весь огонь на себя',
 'description_ru': 'Попасть в команду к капитану танку 5 дива и выше.',
 'description_en': 'Get into a team with a captain tank 5 div and above.'},
    {'category': 'team',
 'slug': 'support-above-5-division',
 'name': 'Умрёшь только когда я скажу',
 'description_ru': 'Попасть в команду к капитану саппорту 5 дива и выше.',
 'description_en': 'Get into a team with a captain support 5 div and above.'},
    {'category': 'team',
 'slug': 'lfs-4500',
 'name': 'LFS 20 EST 4.5k+',
 'description_ru': 'Попасться с одним и тем же игроком 3+ раза.',
 'description_en': 'Get caught with the same player 3+ times.'},
    {'category': 'team',
 'slug': 'im-screwed-run',
 'name': 'Я конченный, бегите',
 'description_ru': 'Отыграть весь турик не сменив персонажа.',
 'description_en': 'Play the whole tournament without changing the character.'},
    {'category': 'team',
 'slug': 'we-work-with-what-we-have',
 'name': 'Работаем с тем, что есть',
 'description_ru': 'Заролиться с тиммейтом OTP в команду.',
 'description_en': 'Roll with a OTP teammate into a team.'},
    {'category': 'team',
 'slug': 'were-so-fucked',
 'name': 'Какая же нам пи№#а',
 'description_ru': 'Заролиться в команду с 3+ OTP тиммейтами.',
 'description_en': 'Roll into a team with 3+ OTP teammates.'},
    {'category': 'standing',
 'slug': 'beginners-are-lucky',
 'name': 'Новичкам везёт',
 'description_ru': 'Пройти во второй день с новичком в команде.',
 'description_en': 'Pass to the second day with a newcomer in the team.'},
    {'category': 'standing',
 'slug': 'were-not-suckers',
 'name': 'Да не лохи мы…',
 'description_ru': 'Отдать финал турнира 2-3.',
 'description_en': 'Give the final of the tournament 2-3.'},
    {'category': 'standing',
 'slug': 'reverse-sweep-champion',
 'name': 'Reverse Sweep Champion',
 'description_ru': 'Выиграть турнир, упадя в нижнюю сетку.',
 'description_en': 'Win a tournament by falling into the lower bracket.'},
    {'category': 'standing',
 'slug': 'to-the-bottom',
 'name': 'На дно!!!',
 'description_ru': 'Отлететь в первый день со счётом 0-10 заняв последнее место в своей группе.',
 'description_en': 'Take off on the first day with a score of 0-10, taking the last place in your group.'},
    {'category': 'standing',
 'slug': 'samurai-has-no-purpose',
 'name': 'Самураю нет цели...',
 'description_ru': 'Не выйти во второй день ни разу.',
 'description_en': 'Not to go out on the second day even once.'},
    {'category': 'standing',
 'slug': 'the-best-among-the-best',
 'name': 'Мы лучшие среди лучших',
 'description_ru': 'Стать топ 1 своей группы в первый день со счётом 10-0.',
 'description_en': 'Become the top 1 of your group on the first day with a score of 10-0.'},
    {'category': 'standing',
 'slug': 'revenge-is-sweet',
 'name': 'Переигран и уничтожен',
 'description_ru': 'Победить соперника, который ранее вас выиграл.',
 'description_en': 'Defeat an opponent who previously beat you.'},
    {'category': 'standing',
 'slug': 'dirty-smurf',
 'name': 'Грязный смурф',
 'description_ru': 'Стать чемпионом в свой первый турнир.',
 'description_en': 'Become a champion in your first tournament.'},
    {'category': 'standing',
 'slug': 'anchor-in-my-throat',
 'name': 'Якорь мне в глотку',
 'description_ru': 'Выиграть турик, имея в команде тиммейта 20 дива.',
 'description_en': 'Win the tournament with a teammate 20 div.'},
    {'category': 'standing',
 'slug': 'win-2-plus-consecutive',
 'name': 'Мне просто повезло',
 'description_ru': 'Выиграть 2+ турнира подряд.',
 'description_en': 'Win 2+ tournaments in a row.'},
    {'category': 'standing',
 'slug': 'five-second-day-streak',
 'name': 'Да нормальный у меня див!',
 'description_ru': 'Выйти во второй день 5 турниров подряд',
 'description_en': 'Go out on the second day 5 tournaments in a row'},
    {'category': 'standing',
 'slug': 'i-killed-i-stole',
 'name': 'Я УБИВАЛ Я ВОРОВАЛ',
 'description_ru': 'Добраться до финала, пройдя по всей нижней сетке.',
 'description_en': 'Get to the final by going through the entire lower bracket.'},
    {'category': 'standing',
 'slug': 'well-balanced',
 'name': 'Забаланшенные',
 'description_ru': 'Сыграть все матчи в группе в ничью.',
 'description_en': 'Play all matches in the group in a draw.'},
    {'category': 'match',
 'slug': 'friendly',
 'name': 'Френдли',
 'description_ru': 'Сыграть карту с 0 убийствами.',
 'description_en': 'Play a map with 0 kills.'},
    {'category': 'match',
 'slug': 'boris_dick',
 'name': 'Борис Хрен Попадешь',
 'description_ru': 'Выиграть карту ни умерев ни разу.',
 'description_en': 'Win a card without dying once.'},
    {'category': 'match',
 'slug': 'just_dont_fuck_around',
 'name': 'Главное не хукнись',
 'description_ru': 'Умереть за карту 20+ раз',
 'description_en': 'Die for a map 20+ times'},
    {'category': 'match',
 'slug': 'john_wick',
 'name': 'Джон Уик',
 'description_ru': 'Сделать более 60 элимов за карту',
 'description_en': 'Make over 60 eliminations per map'},
    {'category': 'match',
 'slug': 'the-shift-factory-is-done',
 'name': 'Смена на заводе отработана',
 'description_ru': 'Нахилять более 30000 ед. хила за карту',
 'description_en': 'Heal for more than 30,000 hit points per map'},
    {'category': 'match',
 'slug': 'shooting_and_screaming',
 'name': 'РАБОТАЕМ ЕКАТЕРИНА!',
 'description_ru': 'Нанести более 35000 ед. урона за карту',
 'description_en': 'Deal more than 35000 damage per map'},
    {'category': 'match',
 'slug': 'fiasko',
 'name': 'Это фиаско братан',
 'description_ru': 'Упасть за карту от бупа 3+ раза за карту',
 'description_en': 'Fall for a map from a boop 3+ times per map'},
    {'category': 'match',
 'slug': 'boop_master',
 'name': 'Чувак это яма',
 'description_ru': 'Бупнуть за карту противника 3+ раза за карту',
 'description_en': 'Boop the opponent 3+ times per map'},
    {'category': 'match',
 'slug': 'bullet-is-not-stupid',
 'name': 'Пуля не дура',
 'description_ru': 'Убить 10+ человек за карту хедшотом',
 'description_en': 'Kill 10+ people per map with headshots'},
    {'category': 'match',
 'slug': 'balanced',
 'name': 'Набалансил',
 'description_ru': 'Сыграть матч с близостью 0%',
 'description_en': 'Play a match with a close 0%'},
    {'category': 'match',
 'slug': 'hard_game',
 'name': 'Я сосал меня е&%ли',
 'description_ru': 'Сыграть матч с близостью 100%',
 'description_en': 'Play a match with a close 100%'},
    {'category': 'match',
 'slug': '7_years_in_azkaban',
 'name': '7 лет в Азкабане',
 'description_ru': 'Сыграть матч длительностью 25+ минут',
 'description_en': 'Play a match lasting 25+ minutes'},
    {'category': 'match',
 'slug': 'fast',
 'name': 'Скорострел',
 'description_ru': 'Сыграть матч длительностью максимум 5 мин',
 'description_en': 'Play a match lasting a maximum of 5 minutes'},
)
