"""Pick-ban ruleset v2 — the pure engine behind the constructor.

No DB, no service imports: every service may import this. The design document
is ``docs/plans/2026-09-28-pick-ban-constructor.md``; each module carries the
section it implements.

- :mod:`.schema` — the ruleset document and the resolved step (§1, §3)
- :mod:`.registry` — condition leaves, constraint specs, the evaluator (§2)
- :mod:`.validate` — what may be saved (§1, §2)
- :mod:`.compile` — phase selection, round resolution, v1 conversion (§3, §11)
- :mod:`.runtime` — submissions, cursor, eligibility, projection (§5)
- :mod:`.presets` / :mod:`.preview` — starting points and the series preview (§6, §10, §12)
"""

from .compile import (
    LEAD_BANS,
    build_sequence_for_best_of,
    build_slot_sequence,
    phase_matches,
    resolve_round,
    resolve_sides,
    ruleset_from_v1,
    select_phase,
    steps_from_v1_tokens,
)
from .presets import PRESETS, PRESETS_BY_ID, Preset
from .preview import preview_series
from .registry import (
    CONSTRAINTS,
    HERO_GROUPS,
    LEAVES,
    AppliedItem,
    ConstraintSpec,
    History,
    ItemCtx,
    LeafSpec,
    ParamSpec,
    RoundCtx,
    catalog,
    evaluate,
    leaf,
    normalize_group,
)
from .runtime import (
    AVAILABLE,
    BANNED,
    DRAFT,
    LOCKED,
    PICKED,
    PROTECTED,
    REVEALED,
    SYSTEM_PICKED_BY,
    VOIDED,
    CarriedBan,
    DisputeState,
    EligibleSet,
    EntryLike,
    RuntimeCtx,
    SubmissionLike,
    TargetPlayer,
    applied_items,
    carried_bans,
    current_attempt,
    current_step,
    dispute_target,
    effective_min,
    filter_pool,
    eligible_items,
    history_of,
    project_entries,
    random_fill,
    ready_to_reveal,
    resolve_system_step,
    side_submission,
    step_progress,
    undo_target,
    validate_items,
    visible_submissions,
)
from .schema import (
    Condition,
    Constraint,
    DisputeRule,
    Issue,
    Phase,
    ResolvedStep,
    Ruleset,
    RulesetError,
    Step,
    parse_ruleset,
    resolved_steps_from_json,
)
from .validate import validate_ruleset

__all__ = (
    "CONSTRAINTS",
    "HERO_GROUPS",
    "LEAD_BANS",
    "LEAVES",
    "AVAILABLE",
    "BANNED",
    "DRAFT",
    "LOCKED",
    "PICKED",
    "PROTECTED",
    "REVEALED",
    "SYSTEM_PICKED_BY",
    "VOIDED",
    "PRESETS",
    "PRESETS_BY_ID",
    "AppliedItem",
    "CarriedBan",
    "Condition",
    "Constraint",
    "ConstraintSpec",
    "DisputeRule",
    "DisputeState",
    "EligibleSet",
    "EntryLike",
    "History",
    "Issue",
    "ItemCtx",
    "LeafSpec",
    "ParamSpec",
    "Phase",
    "Preset",
    "ResolvedStep",
    "RoundCtx",
    "Ruleset",
    "RulesetError",
    "RuntimeCtx",
    "Step",
    "SubmissionLike",
    "TargetPlayer",
    "applied_items",
    "build_sequence_for_best_of",
    "build_slot_sequence",
    "carried_bans",
    "catalog",
    "current_attempt",
    "current_step",
    "dispute_target",
    "effective_min",
    "filter_pool",
    "eligible_items",
    "evaluate",
    "history_of",
    "leaf",
    "normalize_group",
    "parse_ruleset",
    "phase_matches",
    "preview_series",
    "project_entries",
    "random_fill",
    "ready_to_reveal",
    "resolve_round",
    "resolve_sides",
    "resolve_system_step",
    "resolved_steps_from_json",
    "ruleset_from_v1",
    "select_phase",
    "side_submission",
    "step_progress",
    "steps_from_v1_tokens",
    "undo_target",
    "validate_items",
    "validate_ruleset",
    "visible_submissions",
)
