#!/usr/bin/env node
/**
 * Dump the gateway's public+admin OpenAPI docs and generate
 * `src/types/api.generated.ts`.
 *
 * Needs `go` on PATH (the dump command lives in gateway/cmd/dump-openapi).
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const frontend = join(here, "..");
const gateway = join(frontend, "..", "gateway");
const outFile = join(frontend, "src/types/api.generated.ts");

function dump(kind) {
  const r = spawnSync("go", ["run", "./cmd/dump-openapi", kind], {
    cwd: gateway,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024
  });
  if (r.status !== 0) {
    process.stderr.write(r.stderr || "");
    throw new Error(`dump-openapi ${kind} failed (${r.status})`);
  }
  return JSON.parse(r.stdout);
}

const publicDoc = dump("public");
const adminDoc = dump("admin");
const merged = {
  ...publicDoc,
  paths: { ...publicDoc.paths, ...adminDoc.paths },
  components: {
    ...publicDoc.components,
    schemas: {
      ...(publicDoc.components?.schemas ?? {}),
      ...(adminDoc.components?.schemas ?? {})
    }
  }
};

const ast = await openapiTS(merged, { enum: true });
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `/* eslint-disable */
// Generated by scripts/gen-api.mjs — do not edit.
// Regenerate: bun run gen:api

${astToString(ast)}`
);
console.error(`wrote ${outFile}`);
