"""Registration form schema: the model, its invariants and the builtin catalog."""

from shared.domain.forms.builtins import (
    BUILTIN_KEYS,
    DEFAULT_PATTERNS,
    IDENTITY_KEY_PREFIX,
    IDENTITY_PROVIDERS,
    BattleTagParams,
    BuiltinSpec,
    IdentityParams,
    RolesParams,
    TopHeroesParams,
    builtin_spec,
    default_pattern,
    identity_key,
    identity_provider,
    is_builtin_key,
)
from shared.domain.forms.schema import (
    KEY_PATTERN,
    OPTION_KINDS,
    Condition,
    ConditionOp,
    FieldKind,
    FieldValidation,
    FormField,
    FormSchema,
    FormSection,
    Visibility,
    default_schema,
    schema_from_form,
)

__all__ = (
    "BUILTIN_KEYS",
    "DEFAULT_PATTERNS",
    "IDENTITY_KEY_PREFIX",
    "IDENTITY_PROVIDERS",
    "KEY_PATTERN",
    "OPTION_KINDS",
    "BattleTagParams",
    "BuiltinSpec",
    "Condition",
    "ConditionOp",
    "FieldKind",
    "FieldValidation",
    "FormField",
    "FormSchema",
    "FormSection",
    "IdentityParams",
    "RolesParams",
    "TopHeroesParams",
    "Visibility",
    "builtin_spec",
    "default_pattern",
    "default_schema",
    "identity_key",
    "identity_provider",
    "is_builtin_key",
    "schema_from_form",
)
