"""initial_v5

Revision ID: a7634c02717d
Revises: 
Create Date: 2026-04-03 16:19:11.908753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7634c02717d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS balancer")
    op.create_table('analytics_algorithms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('gamemode',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hero',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('tank', 'damage', 'support', name='heroclass'), nullable=False),
    sa.Column('color', sa.String(), server_default='#ffffff', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspace',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)
    op.create_table('achievement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description_ru', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('hero_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_slug'), 'achievement', ['slug'], unique=True)
    op.create_table('auth_user_player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_user_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gamemode_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['gamemode_id'], ['gamemode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_connections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id', 'provider', name='uq_user_provider'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index(op.f('ix_oauth_connections_provider'), 'oauth_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connections_provider_user_id'), 'oauth_connections', ['provider_user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('challonge_id', sa.Integer(), nullable=True),
    sa.Column('challonge_slug', sa.String(), nullable=True),
    sa.Column('is_league', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_workspace_id'), 'tournament', ['workspace_id'], unique=False)
    op.create_table('user_battle_tag',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('battle_tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_battle_tag_battle_tag'), 'user_battle_tag', ['battle_tag'], unique=True)
    op.create_index(op.f('ix_user_battle_tag_name'), 'user_battle_tag', ['name'], unique=False)
    op.create_table('user_discord',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_discord_name'), 'user_discord', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_twitch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_twitch_name'), 'user_twitch', ['name'], unique=True)
    op.create_table('workspace_member',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('auth_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), server_default='member', nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'auth_user_id')
    )
    op.create_index(op.f('ix_workspace_member_auth_user_id'), 'workspace_member', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('balance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('saved_by', sa.BigInteger(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_status', sa.String(length=32), nullable=True),
    sa.Column('export_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['saved_by'], ['auth_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', name='uq_balancer_balance_tournament'),
    schema='balancer'
    )
    op.create_index(op.f('ix_balancer_balance_tournament_id'), 'balance', ['tournament_id'], unique=False, schema='balancer')
    op.create_table('tournament_sheet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=False),
    sa.Column('gid', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('header_row_json', sa.JSON(), nullable=True),
    sa.Column('column_mapping_json', sa.JSON(), nullable=True),
    sa.Column('role_mapping_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', name='uq_balancer_tournament_sheet_tournament'),
    schema='balancer'
    )
    op.create_index(op.f('ix_balancer_tournament_sheet_tournament_id'), 'tournament_sheet', ['tournament_id'], unique=False, schema='balancer')
    op.create_table('log_processing_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='log_processing_status'), nullable=False),
    sa.Column('source', sa.Enum('upload', 'discord', 'manual', name='log_processing_source'), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_processing_record_tournament_id'), 'log_processing_record', ['tournament_id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balancer_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avg_sr', sa.Float(), nullable=False),
    sa.Column('total_sr', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.BigInteger(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_captain_id'), 'team', ['captain_id'], unique=False)
    op.create_index(op.f('ix_team_tournament_id'), 'team', ['tournament_id'], unique=False)
    op.create_table('tournament_discord_channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id')
    )
    op.create_index(op.f('ix_tournament_discord_channel_channel_id'), 'tournament_discord_channel', ['channel_id'], unique=True)
    op.create_table('tournament_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_groups', sa.Boolean(), nullable=False),
    sa.Column('challonge_id', sa.Integer(), nullable=True),
    sa.Column('challonge_slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_group_tournament_id'), 'tournament_group', ['tournament_id'], unique=False)
    op.create_table('analytics_predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('algorithm_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('predicted_place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['analytics_algorithms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_predictions_algorithm_id'), 'analytics_predictions', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_analytics_predictions_team_id'), 'analytics_predictions', ['team_id'], unique=False)
    op.create_index(op.f('ix_analytics_predictions_tournament_id'), 'analytics_predictions', ['tournament_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('battle_tag', sa.String(length=255), nullable=False),
    sa.Column('battle_tag_normalized', sa.String(length=255), nullable=False),
    sa.Column('smurf_tags_json', sa.JSON(), nullable=True),
    sa.Column('twitch_nick', sa.String(length=255), nullable=True),
    sa.Column('discord_nick', sa.String(length=255), nullable=True),
    sa.Column('stream_pov', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_tournament_text', sa.Text(), nullable=True),
    sa.Column('primary_role', sa.String(length=64), nullable=True),
    sa.Column('additional_roles_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_row_json', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_sheet_id'], ['balancer.tournament_sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'battle_tag_normalized', name='uq_balancer_application_tournament_tag'),
    schema='balancer'
    )
    op.create_index(op.f('ix_balancer_application_battle_tag_normalized'), 'application', ['battle_tag_normalized'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_application_tournament_id'), 'application', ['tournament_id'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_application_tournament_sheet_id'), 'application', ['tournament_sheet_id'], unique=False, schema='balancer')
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_id', sa.BigInteger(), nullable=False),
    sa.Column('exported_team_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('balancer_name', sa.String(length=255), nullable=False),
    sa.Column('captain_battle_tag', sa.String(length=255), nullable=True),
    sa.Column('avg_sr', sa.Float(), nullable=False),
    sa.Column('total_sr', sa.Integer(), nullable=False),
    sa.Column('roster_json', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balancer.balance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exported_team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='balancer'
    )
    op.create_index(op.f('ix_balancer_team_balance_id'), 'team', ['balance_id'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_team_exported_team_id'), 'team', ['exported_team_id'], unique=False, schema='balancer')
    op.create_table('challonge_team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('challonge_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tournament_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('closeness', sa.Float(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_group_id', sa.BigInteger(), nullable=True),
    sa.Column('challonge_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'OPEN', name='encounterstatus'), nullable=False),
    sa.Column('has_logs', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_group_id'], ['tournament_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_away_team_id'), 'encounter', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_encounter_home_team_id'), 'encounter', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_encounter_round'), 'encounter', ['round'], unique=False)
    op.create_index('ix_encounter_tournament_group', 'encounter', ['tournament_id', 'tournament_group_id'], unique=False)
    op.create_index(op.f('ix_encounter_tournament_group_id'), 'encounter', ['tournament_group_id'], unique=False)
    op.create_index(op.f('ix_encounter_tournament_id'), 'encounter', ['tournament_id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('secondary', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('div', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('tank', 'damage', 'support', name='heroclass'), nullable=True),
    sa.Column('is_substitution', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('related_player_id', sa.BigInteger(), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('is_newcomer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_newcomer_role', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['related_player_id'], ['player.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_team_user', 'player', ['team_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_player_tournament_id'), 'player', ['tournament_id'], unique=False)
    op.create_index('ix_player_user_not_sub', 'player', ['user_id', 'tournament_id'], unique=False, postgresql_where=sa.text('is_substitution = false'))
    op.create_index('ix_player_user_tournament', 'player', ['user_id', 'tournament_id'], unique=False)
    op.create_table('standing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('overall_position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('draw', sa.Integer(), nullable=False),
    sa.Column('lose', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('buchholz', sa.Float(), nullable=True),
    sa.Column('tb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tournament_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'group_id', 'team_id')
    )
    op.create_index(op.f('ix_standing_group_id'), 'standing', ['group_id'], unique=False)
    op.create_index(op.f('ix_standing_team_id'), 'standing', ['team_id'], unique=False)
    op.create_index(op.f('ix_standing_tournament_id'), 'standing', ['tournament_id'], unique=False)
    op.create_index('ix_standing_tournament_position', 'standing', ['tournament_id', 'overall_position'], unique=False)
    op.create_table('analytics_shifts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('algorithm_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('shift', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['analytics_algorithms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_shifts_algorithm_id'), 'analytics_shifts', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_analytics_shifts_player_id'), 'analytics_shifts', ['player_id'], unique=False)
    op.create_index(op.f('ix_analytics_shifts_tournament_id'), 'analytics_shifts', ['tournament_id'], unique=False)
    op.create_table('analytics_tournament',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('shift_one', sa.Integer(), nullable=True),
    sa.Column('shift_two', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_tournament_player_id'), 'analytics_tournament', ['player_id'], unique=False)
    op.create_index(op.f('ix_analytics_tournament_tournament_id'), 'analytics_tournament', ['tournament_id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('battle_tag', sa.String(length=255), nullable=False),
    sa.Column('battle_tag_normalized', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_entries_json', sa.JSON(), nullable=True),
    sa.Column('is_flex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('primary_role', sa.String(length=32), nullable=True),
    sa.Column('secondary_roles_json', sa.JSON(), nullable=True),
    sa.Column('division_number', sa.Integer(), nullable=True),
    sa.Column('rank_value', sa.Integer(), nullable=True),
    sa.Column('is_in_pool', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['balancer.application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_balancer_player_application'),
    schema='balancer'
    )
    op.create_index(op.f('ix_balancer_player_application_id'), 'player', ['application_id'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_player_battle_tag_normalized'), 'player', ['battle_tag_normalized'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_player_tournament_id'), 'player', ['tournament_id'], unique=False, schema='balancer')
    op.create_index(op.f('ix_balancer_player_user_id'), 'player', ['user_id'], unique=False, schema='balancer')
    op.create_table('match',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('log_name', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.BigInteger(), nullable=False),
    sa.Column('map_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_away_team_id'), 'match', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_match_encounter_id'), 'match', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_match_home_team_id'), 'match', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_match_map_id'), 'match', ['map_id'], unique=False)
    op.create_table('achievement_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_assists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hero_id', sa.BigInteger(), nullable=True),
    sa.Column('related_team_id', sa.BigInteger(), nullable=True),
    sa.Column('related_user_id', sa.BigInteger(), nullable=True),
    sa.Column('related_hero_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Enum('OffensiveAssist', 'DefensiveAssist', 'UltimateCharged', 'UltimateStart', 'UltimateEnd', 'HeroSwap', 'MercyRez', 'EchoDuplicateStart', 'EchoDuplicateEnd', name='matchevent'), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_assists_match_id'), 'match_assists', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_assists_team_id'), 'match_assists', ['team_id'], unique=False)
    op.create_index(op.f('ix_match_assists_user_id'), 'match_assists', ['user_id'], unique=False)
    op.create_table('match_kill_feed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('fight', sa.Integer(), nullable=False),
    sa.Column('ability', sa.Enum('PrimaryFire', 'SecondaryFire', 'Ability1', 'Ability2', 'Ultimate', 'Melee', 'Crouch', name='abilityevent'), nullable=True),
    sa.Column('killer_id', sa.BigInteger(), nullable=False),
    sa.Column('killer_hero_id', sa.BigInteger(), nullable=False),
    sa.Column('killer_team_id', sa.BigInteger(), nullable=False),
    sa.Column('victim_id', sa.BigInteger(), nullable=False),
    sa.Column('victim_team_id', sa.BigInteger(), nullable=False),
    sa.Column('victim_hero_id', sa.BigInteger(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('is_critical_hit', sa.Boolean(), nullable=False),
    sa.Column('is_environmental', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['killer_hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['killer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['killer_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_kill_feed_killer_id'), 'match_kill_feed', ['killer_id'], unique=False)
    op.create_index(op.f('ix_match_kill_feed_match_id'), 'match_kill_feed', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_kill_feed_victim_id'), 'match_kill_feed', ['victim_id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hero_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Enum('Eliminations', 'FinalBlows', 'Deaths', 'AllDamageDealt', 'BarrierDamageDealt', 'HeroDamageDealt', 'HealingDealt', 'HealingReceived', 'SelfHealing', 'DamageTaken', 'DamageBlocked', 'DefensiveAssists', 'OffensiveAssists', 'UltimatesEarned', 'UltimatesUsed', 'MultikillBest', 'Multikills', 'SoloKills', 'ObjectiveKills', 'EnvironmentalKills', 'EnvironmentalDeaths', 'CriticalHits', 'CriticalHitAccuracy', 'ScopedAccuracy', 'ScopedCriticalHitAccuracy', 'ScopedCriticalHitKills', 'ShotsFired', 'ShotsHit', 'ShotsMissed', 'ScopedShotsFired', 'ScopedShotsHit', 'WeaponAccuracy', 'HeroTimePlayed', 'Performance', 'PerformancePoints', 'KD', 'KDA', 'DamageDelta', 'FBE', 'DamageFB', 'Assists', name='logstatsname'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_statistics_hero_id'), 'match_statistics', ['hero_id'], unique=False)
    op.create_index(op.f('ix_match_statistics_match_id'), 'match_statistics', ['match_id'], unique=False)
    op.create_index('ix_match_statistics_match_name_round', 'match_statistics', ['match_id', 'name', 'round'], unique=False)
    op.create_index('ix_match_statistics_match_user_round', 'match_statistics', ['match_id', 'user_id', 'round'], unique=False)
    op.create_index(op.f('ix_match_statistics_name'), 'match_statistics', ['name'], unique=False)
    op.create_index(op.f('ix_match_statistics_round'), 'match_statistics', ['round'], unique=False)
    op.create_index(op.f('ix_match_statistics_team_id'), 'match_statistics', ['team_id'], unique=False)
    op.create_index('ix_match_statistics_user_hero_r0', 'match_statistics', ['user_id', 'hero_id', 'name'], unique=False, postgresql_where=sa.text('round = 0 AND hero_id IS NOT NULL'))
    op.create_index(op.f('ix_match_statistics_user_id'), 'match_statistics', ['user_id'], unique=False)
    op.create_index('ix_match_statistics_user_name_r0', 'match_statistics', ['user_id', 'name'], unique=False, postgresql_where=sa.text('round = 0 AND hero_id IS NULL'))
    op.create_index('ix_match_statistics_user_round_name', 'match_statistics', ['user_id', 'round', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_statistics_user_round_name', table_name='match_statistics')
    op.drop_index('ix_match_statistics_user_name_r0', table_name='match_statistics', postgresql_where=sa.text('round = 0 AND hero_id IS NULL'))
    op.drop_index(op.f('ix_match_statistics_user_id'), table_name='match_statistics')
    op.drop_index('ix_match_statistics_user_hero_r0', table_name='match_statistics', postgresql_where=sa.text('round = 0 AND hero_id IS NOT NULL'))
    op.drop_index(op.f('ix_match_statistics_team_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_round'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_name'), table_name='match_statistics')
    op.drop_index('ix_match_statistics_match_user_round', table_name='match_statistics')
    op.drop_index('ix_match_statistics_match_name_round', table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_match_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_hero_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index(op.f('ix_match_kill_feed_victim_id'), table_name='match_kill_feed')
    op.drop_index(op.f('ix_match_kill_feed_match_id'), table_name='match_kill_feed')
    op.drop_index(op.f('ix_match_kill_feed_killer_id'), table_name='match_kill_feed')
    op.drop_table('match_kill_feed')
    op.drop_index(op.f('ix_match_assists_user_id'), table_name='match_assists')
    op.drop_index(op.f('ix_match_assists_team_id'), table_name='match_assists')
    op.drop_index(op.f('ix_match_assists_match_id'), table_name='match_assists')
    op.drop_table('match_assists')
    op.drop_table('achievement_user')
    op.drop_index(op.f('ix_match_map_id'), table_name='match')
    op.drop_index(op.f('ix_match_home_team_id'), table_name='match')
    op.drop_index(op.f('ix_match_encounter_id'), table_name='match')
    op.drop_index(op.f('ix_match_away_team_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_balancer_player_user_id'), table_name='player', schema='balancer')
    op.drop_index(op.f('ix_balancer_player_tournament_id'), table_name='player', schema='balancer')
    op.drop_index(op.f('ix_balancer_player_battle_tag_normalized'), table_name='player', schema='balancer')
    op.drop_index(op.f('ix_balancer_player_application_id'), table_name='player', schema='balancer')
    op.drop_table('player', schema='balancer')
    op.drop_index(op.f('ix_analytics_tournament_tournament_id'), table_name='analytics_tournament')
    op.drop_index(op.f('ix_analytics_tournament_player_id'), table_name='analytics_tournament')
    op.drop_table('analytics_tournament')
    op.drop_index(op.f('ix_analytics_shifts_tournament_id'), table_name='analytics_shifts')
    op.drop_index(op.f('ix_analytics_shifts_player_id'), table_name='analytics_shifts')
    op.drop_index(op.f('ix_analytics_shifts_algorithm_id'), table_name='analytics_shifts')
    op.drop_table('analytics_shifts')
    op.drop_index('ix_standing_tournament_position', table_name='standing')
    op.drop_index(op.f('ix_standing_tournament_id'), table_name='standing')
    op.drop_index(op.f('ix_standing_team_id'), table_name='standing')
    op.drop_index(op.f('ix_standing_group_id'), table_name='standing')
    op.drop_table('standing')
    op.drop_index('ix_player_user_tournament', table_name='player')
    op.drop_index('ix_player_user_not_sub', table_name='player', postgresql_where=sa.text('is_substitution = false'))
    op.drop_index(op.f('ix_player_tournament_id'), table_name='player')
    op.drop_index('ix_player_team_user', table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_encounter_tournament_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_tournament_group_id'), table_name='encounter')
    op.drop_index('ix_encounter_tournament_group', table_name='encounter')
    op.drop_index(op.f('ix_encounter_round'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_home_team_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_away_team_id'), table_name='encounter')
    op.drop_table('encounter')
    op.drop_table('challonge_team')
    op.drop_index(op.f('ix_balancer_team_exported_team_id'), table_name='team', schema='balancer')
    op.drop_index(op.f('ix_balancer_team_balance_id'), table_name='team', schema='balancer')
    op.drop_table('team', schema='balancer')
    op.drop_index(op.f('ix_balancer_application_tournament_sheet_id'), table_name='application', schema='balancer')
    op.drop_index(op.f('ix_balancer_application_tournament_id'), table_name='application', schema='balancer')
    op.drop_index(op.f('ix_balancer_application_battle_tag_normalized'), table_name='application', schema='balancer')
    op.drop_table('application', schema='balancer')
    op.drop_index(op.f('ix_analytics_predictions_tournament_id'), table_name='analytics_predictions')
    op.drop_index(op.f('ix_analytics_predictions_team_id'), table_name='analytics_predictions')
    op.drop_index(op.f('ix_analytics_predictions_algorithm_id'), table_name='analytics_predictions')
    op.drop_table('analytics_predictions')
    op.drop_index(op.f('ix_tournament_group_tournament_id'), table_name='tournament_group')
    op.drop_table('tournament_group')
    op.drop_index(op.f('ix_tournament_discord_channel_channel_id'), table_name='tournament_discord_channel')
    op.drop_table('tournament_discord_channel')
    op.drop_index(op.f('ix_team_tournament_id'), table_name='team')
    op.drop_index(op.f('ix_team_captain_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_log_processing_record_tournament_id'), table_name='log_processing_record')
    op.drop_table('log_processing_record')
    op.drop_index(op.f('ix_balancer_tournament_sheet_tournament_id'), table_name='tournament_sheet', schema='balancer')
    op.drop_table('tournament_sheet', schema='balancer')
    op.drop_index(op.f('ix_balancer_balance_tournament_id'), table_name='balance', schema='balancer')
    op.drop_table('balance', schema='balancer')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_auth_user_id'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_user_twitch_name'), table_name='user_twitch')
    op.drop_table('user_twitch')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_discord_name'), table_name='user_discord')
    op.drop_table('user_discord')
    op.drop_index(op.f('ix_user_battle_tag_name'), table_name='user_battle_tag')
    op.drop_index(op.f('ix_user_battle_tag_battle_tag'), table_name='user_battle_tag')
    op.drop_table('user_battle_tag')
    op.drop_index(op.f('ix_tournament_workspace_id'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_oauth_connections_provider_user_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_provider'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_table('map')
    op.drop_table('auth_user_player')
    op.drop_index(op.f('ix_achievement_slug'), table_name='achievement')
    op.drop_table('achievement')
    op.drop_index(op.f('ix_workspace_slug'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_table('user')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('hero')
    op.drop_table('gamemode')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('analytics_algorithms')
    op.execute("DROP SCHEMA IF EXISTS balancer")
    # ### end Alembic commands ###
